### ISSUE TITLE
Modified Dates

### ISSUE THREAD

**Issue by holyr00d** [GODZGamingNetwork/InfamousCheats_2.5.5.23#1]
Hi,

The "date modified" is the same for all files in this. Can you explain what modifications you have done? As a user you know those dates are mixed and updated only when and if the files are.

for eg infamous.dll 2.5.5.13 date = 28/3/18. 2.5.5.23 date = 22/3/18

all of the files in this pack read same date 13/5/18

**Comment by GODZ-Dev** [comment]
I ain’t done no modifications to the files, I just uploaded the latest infamous files so other members can download. Helping the infamous community out.

**Comment by holyr00d** [comment]
cool. thx for reply
